# База данных слов для изучения (50 слов на каждый язык)

WORDS_DATABASE = {
    'en': [  # Английский
        {'word': 'Hello', 'translation': 'Привет', 'category': 'greetings'},
        {'word': 'Goodbye', 'translation': 'До свидания', 'category': 'greetings'},
        {'word': 'Thank you', 'translation': 'Спасибо', 'category': 'phrases'},
        {'word': 'Please', 'translation': 'Пожалуйста', 'category': 'phrases'},
        {'word': 'Sorry', 'translation': 'Извините', 'category': 'phrases'},
        {'word': 'Yes', 'translation': 'Да', 'category': 'basics'},
        {'word': 'No', 'translation': 'Нет', 'category': 'basics'},
        {'word': 'Good morning', 'translation': 'Доброе утро', 'category': 'greetings'},
        {'word': 'Good night', 'translation': 'Спокойной ночи', 'category': 'greetings'},
        {'word': 'How are you?', 'translation': 'Как дела?', 'category': 'phrases'},
        {'word': 'I love you', 'translation': 'Я люблю тебя', 'category': 'phrases'},
        {'word': 'Friend', 'translation': 'Друг', 'category': 'people'},
        {'word': 'Family', 'translation': 'Семья', 'category': 'people'},
        {'word': 'Mother', 'translation': 'Мама', 'category': 'family'},
        {'word': 'Father', 'translation': 'Папа', 'category': 'family'},
        {'word': 'Brother', 'translation': 'Брат', 'category': 'family'},
        {'word': 'Sister', 'translation': 'Сестра', 'category': 'family'},
        {'word': 'Child', 'translation': 'Ребенок', 'category': 'people'},
        {'word': 'Water', 'translation': 'Вода', 'category': 'food'},
        {'word': 'Food', 'translation': 'Еда', 'category': 'food'},
        {'word': 'Bread', 'translation': 'Хлеб', 'category': 'food'},
        {'word': 'Apple', 'translation': 'Яблоко', 'category': 'food'},
        {'word': 'Milk', 'translation': 'Молоко', 'category': 'food'},
        {'word': 'Tea', 'translation': 'Чай', 'category': 'drinks'},
        {'word': 'Coffee', 'translation': 'Кофе', 'category': 'drinks'},
        {'word': 'House', 'translation': 'Дом', 'category': 'places'},
        {'word': 'School', 'translation': 'Школа', 'category': 'places'},
        {'word': 'Work', 'translation': 'Работа', 'category': 'activities'},
        {'word': 'Study', 'translation': 'Учиться', 'category': 'activities'},
        {'word': 'Read', 'translation': 'Читать', 'category': 'verbs'},
        {'word': 'Write', 'translation': 'Писать', 'category': 'verbs'},
        {'word': 'Speak', 'translation': 'Говорить', 'category': 'verbs'},
        {'word': 'Listen', 'translation': 'Слушать', 'category': 'verbs'},
        {'word': 'Understand', 'translation': 'Понимать', 'category': 'verbs'},
        {'word': 'Learn', 'translation': 'Учить', 'category': 'verbs'},
        {'word': 'Teach', 'translation': 'Обучать', 'category': 'verbs'},
        {'word': 'Big', 'translation': 'Большой', 'category': 'adjectives'},
        {'word': 'Small', 'translation': 'Маленький', 'category': 'adjectives'},
        {'word': 'Good', 'translation': 'Хороший', 'category': 'adjectives'},
        {'word': 'Bad', 'translation': 'Плохой', 'category': 'adjectives'},
        {'word': 'New', 'translation': 'Новый', 'category': 'adjectives'},
        {'word': 'Old', 'translation': 'Старый', 'category': 'adjectives'},
        {'word': 'Today', 'translation': 'Сегодня', 'category': 'time'},
        {'word': 'Tomorrow', 'translation': 'Завтра', 'category': 'time'},
        {'word': 'Yesterday', 'translation': 'Вчера', 'category': 'time'},
        {'word': 'Day', 'translation': 'День', 'category': 'time'},
        {'word': 'Night', 'translation': 'Ночь', 'category': 'time'},
        {'word': 'Week', 'translation': 'Неделя', 'category': 'time'},
        {'word': 'Month', 'translation': 'Месяц', 'category': 'time'},
        {'word': 'Year', 'translation': 'Год', 'category': 'time'},
    ],
    'es': [  # Испанский
        {'word': 'Hola', 'translation': 'Привет', 'category': 'greetings'},
        {'word': 'Adiós', 'translation': 'До свидания', 'category': 'greetings'},
        {'word': 'Gracias', 'translation': 'Спасибо', 'category': 'phrases'},
        {'word': 'Por favor', 'translation': 'Пожалуйста', 'category': 'phrases'},
        {'word': 'Lo siento', 'translation': 'Извините', 'category': 'phrases'},
        {'word': 'Sí', 'translation': 'Да', 'category': 'basics'},
        {'word': 'No', 'translation': 'Нет', 'category': 'basics'},
        {'word': 'Buenos días', 'translation': 'Доброе утро', 'category': 'greetings'},
        {'word': 'Buenas noches', 'translation': 'Спокойной ночи', 'category': 'greetings'},
        {'word': '¿Cómo estás?', 'translation': 'Как дела?', 'category': 'phrases'},
        {'word': 'Te quiero', 'translation': 'Я люблю тебя', 'category': 'phrases'},
        {'word': 'Amigo', 'translation': 'Друг', 'category': 'people'},
        {'word': 'Familia', 'translation': 'Семья', 'category': 'people'},
        {'word': 'Madre', 'translation': 'Мама', 'category': 'family'},
        {'word': 'Padre', 'translation': 'Папа', 'category': 'family'},
        {'word': 'Hermano', 'translation': 'Брат', 'category': 'family'},
        {'word': 'Hermana', 'translation': 'Сестра', 'category': 'family'},
        {'word': 'Niño', 'translation': 'Ребенок', 'category': 'people'},
        {'word': 'Agua', 'translation': 'Вода', 'category': 'food'},
        {'word': 'Comida', 'translation': 'Еда', 'category': 'food'},
        {'word': 'Pan', 'translation': 'Хлеб', 'category': 'food'},
        {'word': 'Manzana', 'translation': 'Яблоко', 'category': 'food'},
        {'word': 'Leche', 'translation': 'Молоко', 'category': 'food'},
        {'word': 'Té', 'translation': 'Чай', 'category': 'drinks'},
        {'word': 'Café', 'translation': 'Кофе', 'category': 'drinks'},
        {'word': 'Casa', 'translation': 'Дом', 'category': 'places'},
        {'word': 'Escuela', 'translation': 'Школа', 'category': 'places'},
        {'word': 'Trabajo', 'translation': 'Работа', 'category': 'activities'},
        {'word': 'Estudiar', 'translation': 'Учиться', 'category': 'activities'},
        {'word': 'Leer', 'translation': 'Читать', 'category': 'verbs'},
        {'word': 'Escribir', 'translation': 'Писать', 'category': 'verbs'},
        {'word': 'Hablar', 'translation': 'Говорить', 'category': 'verbs'},
        {'word': 'Escuchar', 'translation': 'Слушать', 'category': 'verbs'},
        {'word': 'Entender', 'translation': 'Понимать', 'category': 'verbs'},
        {'word': 'Aprender', 'translation': 'Учить', 'category': 'verbs'},
        {'word': 'Enseñar', 'translation': 'Обучать', 'category': 'verbs'},
        {'word': 'Grande', 'translation': 'Большой', 'category': 'adjectives'},
        {'word': 'Pequeño', 'translation': 'Маленький', 'category': 'adjectives'},
        {'word': 'Bueno', 'translation': 'Хороший', 'category': 'adjectives'},
        {'word': 'Malo', 'translation': 'Плохой', 'category': 'adjectives'},
        {'word': 'Nuevo', 'translation': 'Новый', 'category': 'adjectives'},
        {'word': 'Viejo', 'translation': 'Старый', 'category': 'adjectives'},
        {'word': 'Hoy', 'translation': 'Сегодня', 'category': 'time'},
        {'word': 'Mañana', 'translation': 'Завтра', 'category': 'time'},
        {'word': 'Ayer', 'translation': 'Вчера', 'category': 'time'},
        {'word': 'Día', 'translation': 'День', 'category': 'time'},
        {'word': 'Noche', 'translation': 'Ночь', 'category': 'time'},
        {'word': 'Semana', 'translation': 'Неделя', 'category': 'time'},
        {'word': 'Mes', 'translation': 'Месяц', 'category': 'time'},
        {'word': 'Año', 'translation': 'Год', 'category': 'time'},
    ],
    'fr': [  # Французский
        {'word': 'Bonjour', 'translation': 'Привет/Здравствуйте', 'category': 'greetings'},
        {'word': 'Au revoir', 'translation': 'До свидания', 'category': 'greetings'},
        {'word': 'Merci', 'translation': 'Спасибо', 'category': 'phrases'},
        {'word': 'Sil vous plaît', 'translation': 'Пожалуйста', 'category': 'phrases'},
        {'word': 'Pardon', 'translation': 'Извините', 'category': 'phrases'},
        {'word': 'Oui', 'translation': 'Да', 'category': 'basics'},
        {'word': 'Non', 'translation': 'Нет', 'category': 'basics'},
        {'word': 'Bonne nuit', 'translation': 'Спокойной ночи', 'category': 'greetings'},
        {'word': 'Comment ça va?', 'translation': 'Как дела?', 'category': 'phrases'},
        {'word': 'Je taime', 'translation': 'Я люблю тебя', 'category': 'phrases'},
        {'word': 'Ami', 'translation': 'Друг', 'category': 'people'},
        {'word': 'Famille', 'translation': 'Семья', 'category': 'people'},
        {'word': 'Mère', 'translation': 'Мама', 'category': 'family'},
        {'word': 'Père', 'translation': 'Папа', 'category': 'family'},
        {'word': 'Frère', 'translation': 'Брат', 'category': 'family'},
        {'word': 'Soeur', 'translation': 'Сестра', 'category': 'family'},
        {'word': 'Enfant', 'translation': 'Ребенок', 'category': 'people'},
        {'word': 'Eau', 'translation': 'Вода', 'category': 'food'},
        {'word': 'Nourriture', 'translation': 'Еда', 'category': 'food'},
        {'word': 'Pain', 'translation': 'Хлеб', 'category': 'food'},
        {'word': 'Pomme', 'translation': 'Яблоко', 'category': 'food'},
        {'word': 'Lait', 'translation': 'Молоко', 'category': 'food'},
        {'word': 'Thé', 'translation': 'Чай', 'category': 'drinks'},
        {'word': 'Café', 'translation': 'Кофе', 'category': 'drinks'},
        {'word': 'Maison', 'translation': 'Дом', 'category': 'places'},
        {'word': 'École', 'translation': 'Школа', 'category': 'places'},
        {'word': 'Travail', 'translation': 'Работа', 'category': 'activities'},
        {'word': 'Étudier', 'translation': 'Учиться', 'category': 'activities'},
        {'word': 'Lire', 'translation': 'Читать', 'category': 'verbs'},
        {'word': 'Écrire', 'translation': 'Писать', 'category': 'verbs'},
        {'word': 'Parler', 'translation': 'Говорить', 'category': 'verbs'},
        {'word': 'Écouter', 'translation': 'Слушать', 'category': 'verbs'},
        {'word': 'Comprendre', 'translation': 'Понимать', 'category': 'verbs'},
        {'word': 'Apprendre', 'translation': 'Учить', 'category': 'verbs'},
        {'word': 'Enseigner', 'translation': 'Обучать', 'category': 'verbs'},
        {'word': 'Grand', 'translation': 'Большой', 'category': 'adjectives'},
        {'word': 'Petit', 'translation': 'Маленький', 'category': 'adjectives'},
        {'word': 'Bon', 'translation': 'Хороший', 'category': 'adjectives'},
        {'word': 'Mauvais', 'translation': 'Плохой', 'category': 'adjectives'},
        {'word': 'Nouveau', 'translation': 'Новый', 'category': 'adjectives'},
        {'word': 'Vieux', 'translation': 'Старый', 'category': 'adjectives'},
        {'word': 'Aujourdhui', 'translation': 'Сегодня', 'category': 'time'},
        {'word': 'Demain', 'translation': 'Завтра', 'category': 'time'},
        {'word': 'Hier', 'translation': 'Вчера', 'category': 'time'},
        {'word': 'Jour', 'translation': 'День', 'category': 'time'},
        {'word': 'Nuit', 'translation': 'Ночь', 'category': 'time'},
        {'word': 'Semaine', 'translation': 'Неделя', 'category': 'time'},
        {'word': 'Mois', 'translation': 'Месяц', 'category': 'time'},
        {'word': 'An', 'translation': 'Год', 'category': 'time'},
    ],
    'de': [  # Немецкий
        {'word': 'Hallo', 'translation': 'Привет', 'category': 'greetings'},
        {'word': 'Auf Wiedersehen', 'translation': 'До свидания', 'category': 'greetings'},
        {'word': 'Danke', 'translation': 'Спасибо', 'category': 'phrases'},
        {'word': 'Bitte', 'translation': 'Пожалуйста', 'category': 'phrases'},
        {'word': 'Entschuldigung', 'translation': 'Извините', 'category': 'phrases'},
        {'word': 'Ja', 'translation': 'Да', 'category': 'basics'},
        {'word': 'Nein', 'translation': 'Нет', 'category': 'basics'},
        {'word': 'Guten Morgen', 'translation': 'Доброе утро', 'category': 'greetings'},
        {'word': 'Gute Nacht', 'translation': 'Спокойной ночи', 'category': 'greetings'},
        {'word': 'Wie geht es dir?', 'translation': 'Как дела?', 'category': 'phrases'},
        {'word': 'Ich liebe dich', 'translation': 'Я люблю тебя', 'category': 'phrases'},
        {'word': 'Freund', 'translation': 'Друг', 'category': 'people'},
        {'word': 'Familie', 'translation': 'Семья', 'category': 'people'},
        {'word': 'Mutter', 'translation': 'Мама', 'category': 'family'},
        {'word': 'Vater', 'translation': 'Папа', 'category': 'family'},
        {'word': 'Bruder', 'translation': 'Брат', 'category': 'family'},
        {'word': 'Schwester', 'translation': 'Сестра', 'category': 'family'},
        {'word': 'Kind', 'translation': 'Ребенок', 'category': 'people'},
        {'word': 'Wasser', 'translation': 'Вода', 'category': 'food'},
        {'word': 'Essen', 'translation': 'Еда', 'category': 'food'},
        {'word': 'Brot', 'translation': 'Хлеб', 'category': 'food'},
        {'word': 'Apfel', 'translation': 'Яблоко', 'category': 'food'},
        {'word': 'Milch', 'translation': 'Молоко', 'category': 'food'},
        {'word': 'Tee', 'translation': 'Чай', 'category': 'drinks'},
        {'word': 'Kaffee', 'translation': 'Кофе', 'category': 'drinks'},
        {'word': 'Haus', 'translation': 'Дом', 'category': 'places'},
        {'word': 'Schule', 'translation': 'Школа', 'category': 'places'},
        {'word': 'Arbeit', 'translation': 'Работа', 'category': 'activities'},
        {'word': 'Lernen', 'translation': 'Учиться', 'category': 'activities'},
        {'word': 'Lesen', 'translation': 'Читать', 'category': 'verbs'},
        {'word': 'Schreiben', 'translation': 'Писать', 'category': 'verbs'},
        {'word': 'Sprechen', 'translation': 'Говорить', 'category': 'verbs'},
        {'word': 'Hören', 'translation': 'Слушать', 'category': 'verbs'},
        {'word': 'Verstehen', 'translation': 'Понимать', 'category': 'verbs'},
        {'word': 'Lernen', 'translation': 'Учить', 'category': 'verbs'},
        {'word': 'Lehren', 'translation': 'Обучать', 'category': 'verbs'},
        {'word': 'Groß', 'translation': 'Большой', 'category': 'adjectives'},
        {'word': 'Klein', 'translation': 'Маленький', 'category': 'adjectives'},
        {'word': 'Gut', 'translation': 'Хороший', 'category': 'adjectives'},
        {'word': 'Schlecht', 'translation': 'Плохой', 'category': 'adjectives'},
        {'word': 'Neu', 'translation': 'Новый', 'category': 'adjectives'},
        {'word': 'Alt', 'translation': 'Старый', 'category': 'adjectives'},
        {'word': 'Heute', 'translation': 'Сегодня', 'category': 'time'},
        {'word': 'Morgen', 'translation': 'Завтра', 'category': 'time'},
        {'word': 'Gestern', 'translation': 'Вчера', 'category': 'time'},
        {'word': 'Tag', 'translation': 'День', 'category': 'time'},
        {'word': 'Nacht', 'translation': 'Ночь', 'category': 'time'},
        {'word': 'Woche', 'translation': 'Неделя', 'category': 'time'},
        {'word': 'Monat', 'translation': 'Месяц', 'category': 'time'},
        {'word': 'Jahr', 'translation': 'Год', 'category': 'time'},
    ]
}